# Allows build project and docker image as a single step
FROM eclipse-temurin:8-jdk-alpine as builder
WORKDIR /opt/app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN --mount=type=cache,target=/root/.m2 ./mvnw dependency:go-offline
COPY ./src ./src
RUN --mount=type=cache,target=/root/.m2 ./mvnw clean install

FROM tomcat:8-jre8-alpine
WORKDIR /usr/local/tomcat/webapps
EXPOSE 8080
COPY --from=builder /opt/app/target/*.war hl7.war
